theme: jekyll-theme-cayman
description: "This GitHub project is Cooler Math Games, a cooler version of the popular website coolmathgames.com"
email: "sea7wa@gmail.com"
webserver: "https://lebronbots.github.io"
markdown: GFM
