theme: jekyll-theme-hacker
description: "This GitHub project is Cooler Math Games, a cooler version of the popular website coolmathgames.com"
email: "shekar.km26@gmail.com"
webserver: "https://coolermathgames.ml"
